baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Pi Sigma Chi Fraternity"
theme = "strata"
# Enable Disqus commenting
# disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
# googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Pi Sigma Chi"
	description = "Different school, different fraternity"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []

	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.jpg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "**I'm Strata**, a super simple<br> responsive site template freebie<br> crafted by [HTML5 UP](//html5up.net)."
		# The icons will be shown if you enter your username
		twitter = ""
		github = ""
		facebook = ""
		linkedin = ""

		copyright = [
			"&copy; Pi Sigma Chi",
			"Design: [HTML5 UP](//html5up.net)",
			"Images: [Unsplash](//unsplash.com/)"
		]

	[params.about]
		hide  = false
		title = "Pi Sigma Chi Fraternity"
		content = "Our story is not one of great unique quality, the distinctiveness, lies within its exceptional brothers. We were founded in 1991, at Pratt Institute in New York, by six gentlemen who sought to establish an organization that would counter stereotypes, promote a moral code (not common to fraternities), and stress academics above all else. We exist by five principles: Academics, Charity, Respect, Love, and Social Development, which is the foundation from which this organization was formed and continues to be the guiding aspect in all pursuits of the Fraternity."


	[params.portfolio]
		hide  = false
		title = "Recent Events"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."


	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "We'd love to hear from you. Please fill out the for below to reach us."

		address = [
			"200 Willoughby Ave",
			"Brooklyn, NY 11205",
			"United States"
		]
		phone = "718-636-3422"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "sebastian.lopez.wilson@gmail.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 10
